[package]
name = "ortie"
description = "CLI to manage OAuth access tokens"
version = "0.1.0"
authors = ["soywod <clement.douin@posteo.net>"]
rust-version = "1.87"
edition = "2021"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["cli", "oauth", "token", "flow", "auth"]
homepage = "https://pimalaya.org"
documentation = "https://github.com/pimalaya/ortie"
repository = "https://github.com/pimalaya/ortie"

[package.metadata.docs.rs]
features = ["rustls-ring", "command"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["rustls-ring", "command"]

# TLS
#
native-tls = ["dep:native-tls"]
rustls-aws = ["dep:rustls", "dep:rustls-platform-verifier", "rustls/aws-lc-rs"]
rustls-ring = ["dep:rustls", "dep:rustls-platform-verifier", "rustls/ring"]

# Storages and hooks
#
command = ["dep:io-process"]
keyring = ["dep:io-keyring"]
notify = ["dep:notify-rust"]

# Vendored (OpenSSL and D-Bus)
#
vendored = ["native-tls?/vendored", "notify-rust?/d_vendored", "io-keyring?/vendored"]

[build-dependencies]
pimalaya-toolbox = { version = "0.0.1", default-features = false, features = ["build"] }

[dependencies]
anyhow = "1"
base64 = "0.22"
clap = { version = "4.4", features = ["derive", "wrap_help"] }
clap_complete = "4.4"
clap_mangen = "0.2"
dirs = "6.0"
http = "1"
humantime = "2.2"
io-keyring = { version = "0.0.1", default-features = false, features = ["serde", "std"], optional = true }
io-oauth = { version = "0.0.1", default-features = false, features = ["oauth2", "pkce"] }
io-process = { version = "0.0.1", default-features = false, features = ["expand", "serde", "std"], optional = true }
io-stream = { version = "0.0.1", default-features = false, features = ["std"] }
log = "0.4"
native-tls = { version = "0.2", optional = true }
notify-rust = { version = "4.11", default-features = false, features = ["dbus"], optional = true }
open = "5.3"
pimalaya-toolbox = { version = "0.0.1", default-features = false, features = ["terminal"] }
rustls = { version = "0.23", default-features = false, features = ["logging", "std", "tls12"], optional = true }
rustls-platform-verifier = { version = "0.5", optional = true }
secrecy = { version = "0.10", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
shellexpand = "3.1"
url = "2.5"

[patch.crates-io]
pimalaya-toolbox.git = "https://github.com/pimalaya/toolbox"
