[accounts.example]

# Make this current account the default one to use when no account is
# specified in the CLI with the --account argument.
#
default = true

# The client credentials
#
client-id = ""
#client-secret.raw = "secret"
#client-secret.command = "pass show example"

# Endpoints, given by your OAuth provider.
#
endpoints.authorization = ""
endpoints.token = ""
#endpoints.redirection = "http://localhost"

# Access token scopes
#
scopes = []

# TLS configuration
#
#tls = "native-tls"
#tls = "rustls-aws"
#tls = "rustls-ring"

# Enables Proof Key for Code Exchange (rfc7636)
#
pkce = false

# Automatically refreshes expired access token when using `ortie token
# show` command.
#
auto-refresh = false

# Token storage
#
# You need 2 different commands: one that reads your token, and one
# that writes freshly issued or refreshed tokens. Mimosa is a good
# candidate, but you can use whatever CLI matching your needs:
#
# https://github.com/pimalaya/mimosa
storage.read.command = ["mimosa", "password", "read", "ortie"]
storage.write.command = ["mimosa", "password", "write", "ortie"]

# Hooks
#
#hooks.on-issue.success.command = []
#hooks.on-issue.success.notify.summary = "Ortie"
#hooks.on-issue.success.notify.body = "Issued access token (expires in $EXPIRES_IN)"
#
#hooks.on-issue.error.command = []
#hooks.on-issue.error.notify.summary = "Ortie"
#hooks.on-issue.error.notify.body = "[$ERROR] Issue access token error\n$ERROR_DESCRIPTION"
#
#hooks.on-refresh.success.command = []
#hooks.on-refresh.success.notify.summary = "Ortie"
#hooks.on-refresh.success.notify.body = "Refreshed access token (expires in $EXPIRES_IN)"
#
#hooks.on-refresh.error.command = []
#hooks.on-refresh.error.notify.summary = "Ortie"
#hooks.on-refresh.error.notify.body = "[$ERROR] Refresh access token error\n$ERROR_DESCRIPTION"
