use std::{borrow::Cow, time::Duration};

use anyhow::{Result, anyhow};
use clap::Parser;
use humantime::format_duration;
use log::debug;
use pimalaya_cli::printer::{Message, Printer};
use serde::{
    Deserialize, Serializer,
    de::value::{Error, StrDeserializer},
};
use url::Url;

use pimalaya_config::secret::Secret;

use crate::{
    authorization_code_grant::{
        authorization_response::AuthorizeParams, pkce::PkceCodeVerifier, state::State,
    },
    cli::account::Account,
    client::OauthClient,
};

/// Resume an existing OAuth 2.0 Authorization Code Grant flow.
///
/// This command can be useful when you initiated an authorization
/// flow in a non-interactive way. After being redirected, this
/// command allows you to complete the authorization flow and get an
/// access and a refresh token from the redirect URI, the initial
/// state as well as the PKCE code verifier.
#[derive(Debug, Parser)]
pub struct AuthResumeCommand {
    /// The URI the user has been redirected to after opening the
    /// authorization URI.
    ///
    /// This URI is not the user redirect URI, but is the redirect URI
    /// generated by the OAuth 2.0 server. When using the auth get
    /// command in an interactive shell, a fake server is spawned in
    /// order to catch this URI.
    #[arg(value_parser = uri_parser)]
    pub redirected_uri: Url,

    /// The state generated during the authorization flow initiation.
    ///
    /// If a state has been generated during the auth get command, it
    /// should be given to the resume command and should match.
    #[arg(long, short, value_parser = state_parser)]
    #[arg(value_name = "VALUE")]
    pub state: Option<State>,

    /// The PKCE code verifier generated during the authorization flow
    /// initiation.
    ///
    /// If PKCE has been enabled during the auth get command, the
    /// generated code should be given to the resume command.
    #[arg(long, short, value_parser = pkce_code_verifier_parser)]
    #[arg(value_name = "CODE")]
    pub pkce: Option<PkceCodeVerifier>,

    /// The redirect URI used during the authorization flow
    /// initiation.
    ///
    /// If a redirect URI was provided during the auth get command, it
    /// must match here.
    #[arg(long, short, value_parser = uri_parser)]
    pub redirect_uri: Option<Url>,
}

impl AuthResumeCommand {
    pub fn execute(self, printer: &mut impl Printer, mut account: Account) -> Result<()> {
        let params = match AuthorizeParams::from(&self.redirected_uri) {
            AuthorizeParams::Success(params) => params,
            AuthorizeParams::Error(params) => {
                let err = anyhow!("Authorization error (code {:?})", params.error);
                return Err(match (params.error_description, params.error_uri) {
                    (None, None) => err,
                    (Some(desc), None) => anyhow!("{desc}").context(err),
                    (None, Some(uri)) => anyhow!("{uri}").context(err),
                    (Some(desc), Some(uri)) => anyhow!("{desc}: {uri}").context(err),
                });
            }
        };

        let state = self.state.as_ref().map(Cow::Borrowed);

        if params.state != state {
            let req = self.state.as_ref().map(|state| state.expose());
            let res = params.state.as_ref().map(|state| state.expose());

            let err = anyhow!("Request state {req:?} differs from response state {res:?}")
                .context("Authorization request and response states do not match");

            return Err(err);
        };

        let client_secret = account.client_secret.clone().map(Secret::get).transpose()?;

        let redirect_uri = self
            .redirect_uri
            .as_ref()
            .map(|uri| Cow::Owned(uri.to_string()))
            .or_else(|| {
                account
                    .redirection_endpoint
                    .as_ref()
                    .map(|uri| Cow::Owned(uri.to_string()))
            });

        let mut client =
            OauthClient::new(&account.token_endpoint, &account.tls, &account.client_id);
        client.client_secret = client_secret;

        let res = client.request_access_token(
            params.code,
            redirect_uri,
            self.pkce.as_ref().map(Cow::Borrowed),
        )?;

        match res {
            Ok(res) => {
                account.write_to_storage(&res)?;

                debug!("execute issue access token success hook");
                account.execute_on_issue_success_hook(&res);

                let msg = "Access token successfully issued";
                let msg = match res.expires_in {
                    None => format!("{msg} (unknown expiry)"),
                    Some(exp) => {
                        let exp = Duration::from_secs(exp as u64 + 1);
                        format!("{msg} (expires in {})", format_duration(exp))
                    }
                };

                printer.out(Message::new(msg))
            }
            Err(res) => {
                debug!("execute issue access token error hook");
                account.execute_on_issue_error_hook(&res);

                let err = anyhow!("Issue access token error (code {:?})", res.error);
                Err(match (res.error_description, res.error_uri) {
                    (None, None) => err,
                    (Some(desc), None) => anyhow!("{desc}").context(err),
                    (None, Some(uri)) => anyhow!("{uri}").context(err),
                    (Some(desc), Some(uri)) => anyhow!("{desc}: {uri}").context(err),
                })
            }
        }
    }
}

pub fn serialize_state<S: Serializer>(state: &State, s: S) -> Result<S::Ok, S::Error> {
    let state = String::from_utf8_lossy(state.expose());
    s.serialize_str(&state)
}

pub fn serialize_pkce_code_verifier<S: Serializer>(
    verifier: &Option<PkceCodeVerifier>,
    s: S,
) -> Result<S::Ok, S::Error> {
    match verifier {
        Some(verifier) => {
            let verifier = String::from_utf8_lossy(verifier.expose());
            s.serialize_str(&verifier)
        }
        None => s.serialize_none(),
    }
}

pub fn uri_parser(url: &str) -> Result<Url, String> {
    Url::parse(url).map_err(|err| err.to_string())
}

pub fn state_parser(state: &str) -> Result<State, String> {
    match State::deserialize(StrDeserializer::<Error>::new(state)) {
        Ok(state) => Ok(state),
        Err(err) => Err(err.to_string()),
    }
}

pub fn pkce_code_verifier_parser(verifier: &str) -> Result<PkceCodeVerifier, String> {
    match verifier.parse() {
        Ok(verifier) => Ok(verifier),
        Err(b) => {
            let err = format!("Invalid 0x{b:x} found in PKCE code verifier: {verifier}");
            Err(err)
        }
    }
}
