//! `auth resume` subcommand: complete an authorization code grant flow.

use std::{borrow::Cow, time::Duration};

use anyhow::{Result, anyhow, bail};
use clap::Parser;
use humantime::format_duration;
use log::debug;
use pimalaya_cli::printer::{Message, Printer};
use serde::{
    Deserialize,
    de::value::{Error, StrDeserializer},
};
use url::Url;

use pimalaya_config::secret::Secret;

use io_oauth::{
    rfc6749::{
        access_token_request::Oauth20RequestAccessTokenParams,
        auth_response::{Oauth20AuthParams, Oauth20AuthParamsValidationError},
        client::Oauth20ClientStd,
        state::Oauth20State,
    },
    rfc7636::pkce::Oauth20PkceCodeVerifier,
};

use crate::{account::Account, config::GrantConfig};

/// Resume an existing OAuth 2.0 Authorization Code Grant flow.
///
/// This command can be useful when you initiated an authorization
/// flow in a non-interactive way. After being redirected, this
/// command allows you to complete the authorization flow and get an
/// access and a refresh token from the redirect URI, the initial
/// state as well as the PKCE code verifier.
#[derive(Debug, Parser)]
pub struct AuthResumeCommand {
    /// The URI the user has been redirected to after opening the
    /// authorization URI.
    ///
    /// This URI is not the user redirect URI, but is the redirect URI
    /// generated by the OAuth 2.0 server. When using the auth get
    /// command in an interactive shell, a fake server is spawned in
    /// order to catch this URI.
    #[arg(value_parser = uri_parser)]
    pub redirected_uri: Url,

    /// The state generated during the authorization flow initiation.
    ///
    /// If a state has been generated during the auth get command, it
    /// should be given to the resume command and should match.
    #[arg(long, short, value_parser = state_parser)]
    #[arg(value_name = "VALUE")]
    pub state: Option<Oauth20State>,

    /// The PKCE code verifier generated during the authorization flow
    /// initiation.
    ///
    /// If PKCE has been enabled during the auth get command, the
    /// generated code should be given to the resume command.
    #[arg(long, short, value_parser = pkce_code_verifier_parser)]
    #[arg(value_name = "CODE")]
    pub pkce: Option<Oauth20PkceCodeVerifier>,

    /// The redirect URI used during the authorization flow
    /// initiation.
    ///
    /// If a redirect URI was provided during the auth get command, it
    /// must match here.
    #[arg(long, short, value_parser = uri_parser)]
    pub redirect_uri: Option<Url>,
}

impl AuthResumeCommand {
    /// Validates the redirected URI then exchanges its authorization
    /// code for a token, persisted to storage with the hooks fired.
    pub fn execute(self, printer: &mut impl Printer, mut account: Account) -> Result<()> {
        // FIXME: interpret the positional input per grant once the
        // device authorization grant path lands.
        if account.grant == GrantConfig::Device {
            bail!("The device authorization grant is not supported yet");
        }

        let Some(token_endpoint) = account.token_endpoint.clone() else {
            bail!("Missing endpoints.token in the account config");
        };

        let code = match Oauth20AuthParams::from(&self.redirected_uri).validate(self.state.as_ref())
        {
            Ok(code) => code,
            Err(Oauth20AuthParamsValidationError::Server(params)) => {
                let err = anyhow!("Authorization error (code {:?})", params.error);
                return Err(match (params.error_description, params.error_uri) {
                    (None, None) => err,
                    (Some(desc), None) => anyhow!("{desc}").context(err),
                    (None, Some(uri)) => anyhow!("{uri}").context(err),
                    (Some(desc), Some(uri)) => anyhow!("{desc}: {uri}").context(err),
                });
            }
            Err(Oauth20AuthParamsValidationError::StateMissing) => {
                return Err(anyhow!("Authorization response is missing state"));
            }
            Err(Oauth20AuthParamsValidationError::StateMismatch) => {
                let req = self.state.as_ref().map(|state| state.expose());
                return Err(
                    anyhow!("Request state {req:?} does not match response state")
                        .context("Authorization request and response states do not match"),
                );
            }
        };

        let client_secret = account.client_secret.clone().map(Secret::get).transpose()?;

        let redirect_uri = self
            .redirect_uri
            .as_ref()
            .map(|uri| Cow::Owned(uri.to_string()))
            .or_else(|| {
                account
                    .redirection_endpoint
                    .as_ref()
                    .map(|uri| Cow::Owned(uri.to_string()))
            });

        let mut client =
            Oauth20ClientStd::connect(token_endpoint, &account.tls, account.client_id.clone())?;
        client.client_secret = client_secret;

        let res = client.request_access_token(Oauth20RequestAccessTokenParams {
            code,
            redirect_uri,
            client_id: account.client_id.as_str().into(),
            client_secret: None,
            pkce_code_verifier: self.pkce.as_ref().map(Cow::Borrowed),
        })?;

        match res {
            Ok(res) => {
                account.write_to_storage(&res)?;

                debug!("execute issue access token success hook");
                account.execute_on_issue_success_hook(&res);

                let msg = "Access token successfully issued";
                let msg = match res.expires_in {
                    None => format!("{msg} (unknown expiry)"),
                    Some(exp) => {
                        let exp = Duration::from_secs(exp as u64 + 1);
                        format!("{msg} (expires in {})", format_duration(exp))
                    }
                };

                printer.out(Message::new(msg))
            }
            Err(res) => {
                debug!("execute issue access token error hook");
                account.execute_on_issue_error_hook(&res);

                let err = anyhow!("Issue access token error (code {:?})", res.error);
                Err(match (res.error_description, res.error_uri) {
                    (None, None) => err,
                    (Some(desc), None) => anyhow!("{desc}").context(err),
                    (None, Some(uri)) => anyhow!("{uri}").context(err),
                    (Some(desc), Some(uri)) => anyhow!("{desc}: {uri}").context(err),
                })
            }
        }
    }
}

/// Clap value parser for URI arguments.
pub fn uri_parser(url: &str) -> Result<Url, String> {
    Url::parse(url).map_err(|err| err.to_string())
}

/// Clap value parser for the CSRF state argument.
pub fn state_parser(state: &str) -> Result<Oauth20State, String> {
    match Oauth20State::deserialize(StrDeserializer::<Error>::new(state)) {
        Ok(state) => Ok(state),
        Err(err) => Err(err.to_string()),
    }
}

/// Clap value parser for the PKCE code verifier argument.
pub fn pkce_code_verifier_parser(verifier: &str) -> Result<Oauth20PkceCodeVerifier, String> {
    match verifier.parse() {
        Ok(verifier) => Ok(verifier),
        Err(b) => {
            let err = format!("Invalid 0x{b:x} found in PKCE code verifier: {verifier}");
            Err(err)
        }
    }
}
