name: Releases

on:
  push:
    tags:
      - v*

jobs:
  release:
    uses: pimalaya/nix/.github/workflows/releases.yml@master
    secrets: inherit
    with:
      project: ortie
      nixpkgs: staging-next
